[env:esp32dev]
platform = espressif32@6.3.2
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
    mathieucarbou/ESPAsyncWebServer@^3.3.0
    mathieucarbou/AsyncTCP@^3.3.0
